=== concord-consortium/teemss/CCProbe/CCProbeXML/labbook.dtd
<?xml encoding="UTF-8"?><!ENTITY % SNOBJECTS "FOLDER | NOTES | DATACOLLECTOR | DRAWING | UNITCONV | IMAGE | EXPOBJECT"><!ENTITY % CCOBJECTS "%SNOBJECTS; | SUPERNOTES"><!ENTITY % boolean "(true | false)"><!ELEMENT LABBOOK (%CCOBJECTS;)*><!ELEMENT FOLDER (%CCOBJECTS;)*><!ATTLIST FOLDER	ID			ID			#REQUIRED><!ELEMENT NOTES (#PCDATA)><!ATTLIST NOTES	ID			ID			#REQUIRED><!ELEMENT DATACOLLECTOR EMPTY><!ATTLIST DATACOLLECTOR	ID			ID			#REQUIRED><!ELEMENT DRAWING EMPTY><!ATTLIST DRAWING	ID			ID			#REQUIRED><!ELEMENT UNITCONV EMPTY><!ATTLIST UNITCONV	ID			ID			#REQUIRED><!ELEMENT IMAGE EMPTY><!ATTLIST IMAGE	ID			ID			#REQUIRED><!ELEMENT SUPERNOTES (SNTEXT,(EMBOBJ)*)><!ATTLIST SUPERNOTES	ID			ID			#REQUIRED><!ELEMENT SNTEXT (SNPARAGRAPH)*><!ATTLIST SNTEXT	indent   	CDATA 		#IMPLIED><!ELEMENT EMBOBJ (%SNOBJECTS;)><!ELEMENT SNPARAGRAPH (#PCDATA)><!ATTLIST SNPARAGRAPH	ID			ID			#REQUIRED	link   		%boolean; 	"false"	color  		CDATA 		"000000"	objlink 	IDREF 		#IMPLIED><!ELEMENT EXPOBJECT EMPTY><!ATTLIST EXPOBJECT	url CDATA #REQUIRED>

=== concord-consortium/teemss/CCProbe/CCProbeXML/testsuite/forwardlinks.xml
<?xml version="1.0"?><!DOCTYPE LABBOOK PUBLIC "-//Concord.ORG//DTD LabBook Description//EN" "../../../DTD/labbook.dtd"><LABBOOK>  <DRAWING ID="drawing2" name="drawing2"/>  <SUPERNOTES ID="forward_linking_test" name="forward_linking_test">    <SNPARAGRAPH linkcolor="0000FF">      forward_linking_test    </SNPARAGRAPH>    <SNPARAGRAPH/>    <SNPARAGRAPH>1. linking from a SNPARAGRAPH</SNPARAGRAPH>    <SNPARAGRAPH/>    <SNPARAGRAPH link="true" linkcolor="FF0000" object="drawing1">      snparagraph text link:drawing1    </SNPARAGRAPH>    <SNPARAGRAPH/>    <SNPARAGRAPH>2. linking from a EMBOBJ</SNPARAGRAPH>    <SNPARAGRAPH/>    <EMBOBJ object="drawing1" link="true" linkcolor="FF0000"/>    <SNPARAGRAPH/>    <SNPARAGRAPH>3. linking from a OBJ-REF in an EMBOBJ</SNPARAGRAPH>    <SNPARAGRAPH/>    <EMBOBJ link="true" linkcolor="FF0000"><OBJ-REF ref="drawing1"/></EMBOBJ>    <SNPARAGRAPH/>    <SNPARAGRAPH>...end of supernote ...</SNPARAGRAPH>  </SUPERNOTES>  <DRAWING ID="drawing1" name="drawing1"/></LABBOOK>
