=== concord-consortium/teemss/TeemssXML/project.dtd
<?xml encoding="UTF-8"?>
<!ENTITY % TEXT1 "#PCDATA|image|ext_image_sequence|ext_image|p"> 
<!ENTITY % TEXT "(%TEXT1;)*">

<!ELEMENT junk (#PCDATA)>
<!ELEMENT project (title, unit+)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST project name CDATA #REQUIRED >
<!ELEMENT unit (title, investigation+)>
<!ATTLIST unit       name CDATA #REQUIRED> 
<!ELEMENT investigation (title, summary, question, intro, think, materials, safety, trial+, hints, analysis, further)>
<!ATTLIST investigation name CDATA #REQUIRED >
<!ELEMENT summary (#PCDATA)>
<!ELEMENT question (#PCDATA)>
<!ELEMENT intro %TEXT;>
<!ELEMENT think %TEXT;>
<!ELEMENT materials (ext_image?,item+)>
<!ELEMENT safety (item+)>
<!ELEMENT trial (%TEXT1; | instructions | steps)*>
<!ATTLIST trial title   CDATA #REQUIRED>
<!ELEMENT instructions (instruction+)>
<!ELEMENT instruction (%TEXT1; | steps)*>
<!ATTLIST instruction title CDATA #REQUIRED>
<!ELEMENT steps (step+)>
<!ELEMENT step (%TEXT1; | steps)*>
<!ELEMENT hints (hint+)>
<!ELEMENT hint (title,heading,body)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body %TEXT;>
<!ELEMENT analysis (data*, steps)>
<!ELEMENT data EMPTY>
<!ATTLIST data trial CDATA #REQUIRED>
<!ELEMENT further (item+)>
<!ELEMENT item %TEXT;>
<!ELEMENT ext_image EMPTY>
<!ATTLIST ext_image type (gif|jpg) "gif">
<!ATTLIST ext_image  name CDATA  #REQUIRED>
<!ELEMENT ext_image_sequence (ext_image+)>
<!ELEMENT image EMPTY>
<!ATTLIST image name CDATA #REQUIRED>
<!ATTLIST image  dir CDATA #REQUIRED>
<!ELEMENT p %TEXT;>

=== concord-consortium/teemss/TeemssXML/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "-//CONCORD.ORG//DTD Param Description//EN" "project.dtd">
<project name="teemss">
  <title>TEEMSS</title>
  <skill-list>
	<skill name="learn stuff">I'm learning xsl haha</skill>
	<skill name="learn other stuff">Of course that means I'm learning XML too.</skill>
  </skill-list>
  <unit name="Motions_and_Forces">
    <title>Motions and Forces</title>
    <investigation name="Air_Cart">
      <title>Air Cart</title>
	  <teacher-notes>
		<teacher-intro>
		  <summary>Testing testing </summary>
		  <skills>
			<skill-ref ref="learn stuff"/>
			<skill-ref ref="learn other stuff"/>
		  </skills>
		</teacher-intro>
		<teacher-discuss>
		  <teacher-overview>This investigation is important because students build a low-friction cart and ramp that will be needed later. Most of this investigation is devoted to construction and testing. This can be most absorbing, but to get the most out of the time, you should encourage students to think about the goal of friction reduction and how the cart design achieves this.
</teacher-overview>
		  <teacher-stage>Before beginning the construction, engage students in a conversation about friction. A good first discussion can be about what it would be like to exist in a world without friction. Here are some questions you might ask, followed by possible responses.
<teacher-questions>
			  <question>When have you experienced very low friction?</question>
			  <answer>Roller-skating, ice skating, skateboarding. Not swimming</answer>
			  <question>What would it be like if every surface was covered by slippery ice?</question>
			  <answer>It would be hard to stand up. Going down stairs would be very dangerous--hanging on the banister would not help much because your hands would slip, too.</answer>
			  <question>Would your bike work in a frictionless world?</question>
			</teacher-questions>
</teacher-stage>
		  <teacher-wrap>If students investigate the effect of mass, they might be in for a surprise. It is natural to assume that the heavier cart will zoom down the ramp faster. Ask students:
</teacher-wrap>
		</teacher-discuss>
		<teacher-background>
The energy lost to friction always ends up as heat energy in the form of random molecular motion. This will come up in later investigations, when the question "where did the energy go?" will be asked again and again. There can be many sources of friction. In the case of the cart, the axle rubs in the straw when it turns. There is some rolling friction as the wheel surface touches and then lifts from the floor. This is much less than if the wheels were locked and dragged across the floor, however! That's why car brakes work: when the wheel is braked, it is dragged along the road instead of being free to roll. It's also why you can steer: it's easier for a wheel to roll in the direction it's steered than to slide sideways, so the car tends to go in that direction, unless the road is icy.
</teacher-background>
		<teacher-timeline>
		  <time-period periods="1" type="setup"/>
		  <time-period periods="1.5" type="trial" number="1"/>
		  <time-period periods=".5" type="trial" number="2"/>
		  <time-period periods="1" type="wrap"/>
		</teacher-timeline>
	  </teacher-notes>
      <summary> Build (and test) an air cart that operates with very
        little friction</summary>
      <question> What happens to a vehicle when there&apos;s very little friction?</question>
      <intro>
        <ext-image dir="images/AirCart" name="smallCart"/> In this
        activity you will build and test an air cart that operates with
        very little friction.</intro>
      <think>
        <p> Have you ever wondered why cars stay on the road when they
          round a corner? Why is it more difficult to round those
          corners when the road is wet or covered with ice? Besides the
          banking of the road (which we will learn about later), the
          tires provide a frictional surface against the surface of the
          road. The ideal car provides friction when you need it
          (turning and braking) but has little when you don&apos;t want
          it (speeding along in a straight line). </p>
        <p> It&apos;s not that easy to make a vehicle move with almost
          no friction. But that&apos;s the goal of this investigation.
          We want a cart that&apos;s almost friction free so that we can
          study the forces on moving objects without being confused by
          the forces due to friction. If a frictionless cart, for
          example, is pushed across the floor, how far do you think the
          cart will go? In your group, predict and explain how different
          forces will affect the motion of a frictionless cart. Write in
          Notes on your handheld computer your ideas about what might
          explain your prediction(s). Refer to Technical Hints to see
          how to use the software. </p>
      </think>
      <materials>
        <ext-image dir="images/AirCart" name="00_cartParts" type="gif"/>
        <item>CC SmartWheel</item>
        <item>cardboard for cart body (12cm x 40cm)</item>
        <item>cardboard for ramp (30cm x 100cm)</item>
        <item>2 - junk CD-ROMs, with snap-in plastic hubs</item>
        <item>aluminum axle (15cm)</item>
        <item>drinking straw</item>
        <item>rubber bumper (popper)</item>
        <item>small paper drinking cup (150 ml)</item>
        <item>small DC motor with leads</item>
        <item>propeller</item>
        <item>2 - new 1.5V AA batteries</item>
        <item>battery holder with leads</item>
        <item>clay (for added weight)</item>
        <item>accelerator acrobat</item>
        <item>wire for support of accelerator acrobat</item>
        <item>books to prop up ramp</item>
        <item>tape</item>
        <item>handheld computer</item>
        <item>CC Lab Book software</item>
        <item>hot-melt (or cold-melt) glue gun and glue sticks</item>
        <item>utility knife</item>
        <item>metal straight edge ruler (metric)</item>
        <item>scissors</item>
      </materials>
      <safety>
        <item> If you are using a hot glue gun, caution should be taken
          until the glue cools and hardens. Burns may result.</item>
        <item> If you are using a utility knife to cut the cardboard,
          extreme care should be taken to prevent cuts. Use a sharp
          blade and get instruction in how to cut against a straightedge.</item>
        <item> If you choose to use the propeller, keep in mind that it
          turns rapidly when it is powered by the battery, so watch out
          for your fingers!</item>
      </safety>
      <trial title="Building an air cart"> To build your air cart follow
        these easy steps! <instructions>
          <instruction title="Making the cardboard foundation">
            <steps>
              <step> Carefully use the utility knife to cut out a 12cm x
                40cm rectangle from cardboard for the air cart body. The
                corrugations in the cardboard should run the long way.
                Your teacher may provide this cardboard piece already cut.</step>
              <step> Mark the slot for the SmartWheel probe. Be sure the
                slot is parallel to the cart length. The slot is 2cm
                wide and 14cm long, starting 4cm from one end of the cart.</step>
              <step> Cut out the slot with a utility knife. Please be
                very careful! <ext-image-sequence>
                  <ext-image dir="images/AirCart" name="01a_cardboard"/>
                  <ext-image dir="images/AirCart" name="01b_slotCutMark"/>
                  <ext-image dir="images/AirCart" name="01c_slotCutOut"/>
                </ext-image-sequence>
              </step>
            </steps>
          </instruction>
          <instruction title="Installing the axles">
            <steps>
              <step>Mark the axle line. It is 8cm from the other end of
                the cart and perpendicular to the long side. You can use
                the corner of a piece of paper to make a perpendicular line.</step>
              <step>Glue the straw to the axle line with hot-melt glue.
                Let it stick out on either side.  </step>
              <step>Cut off each end of the straw a bit longer than the cardboard.</step>
              <step>The finished straw is now ready for the axle.<ext-image-sequence>
                  <ext-image dir="images/AirCart" name="02a_strawMark"/>
                  <ext-image dir="images/AirCart" name="02b_strawGlued"/>
                  <ext-image dir="images/AirCart" name="02c_strawCut"/>
                  <ext-image dir="images/AirCart" name="02d_strawInstall"/>
                </ext-image-sequence>
              </step>
            </steps>
          </instruction>
          <instruction title="Attaching the SmartWheel to the Cart">
            <steps>
              <step>Center the SmartWheel in the slot so that it
                doesn&apos;t rub against the cardboard. Make it exactly
                parallel to the long edge of the cart. This will make
                the cart go straight. The aluminum arm goes against the
                same side of the cardboard as the straw. Mark two screw
                holes with a pencil or pen, one at each end.  </step>
              <step>Make holes where the marks are, using a pencil or
                pen point. Enlarge the holes from both sides, until the
                screws fit snugly into them. The screws are provided
                with the SmartWheel.</step>
              <step>Put the screws through the cardboard from the other
                side, and screw them into the arm of the SmartWheel.
                Tighten them until the heads squeeze the cardboard a
                little bit. A paper clip will work as a screwdriver. </step>
              <step>Now the SmartWheel is in place. It can be taken on
