=== concord-consortium/teemss/XML2LabBook/labbook.dtd
<?xml encoding="UTF-8"?>
<!ENTITY % SNOBJECTS "FOLDER | NOTES | DATACOLLECTOR | DRAWING | UNITCONV | IMAGE | EXPOBJECT | OBJ-REF">
<!ENTITY % CCOBJECTS "%SNOBJECTS; | SUPERNOTES">
<!ENTITY % boolean "(true | false)">
<!ENTITY % probes "(Temperature | Light | SmartWheel | RawData | Force | VoltageCurrent)">


<!ELEMENT LABBOOK (%CCOBJECTS;)*>
<!ATTLIST LABBOOK
	view		(paging | tree)		"tree"
>

<!ELEMENT FOLDER (%CCOBJECTS;)*>
<!ATTLIST FOLDER
	ID			ID					#IMPLIED
	name		CDATA				#IMPLIED
    locked      %boolean;           #IMPLIED
	view		(paging | tree)		"tree"
	url			CDATA				#IMPLIED
>
<!ELEMENT NOTES (#PCDATA)>
<!ATTLIST NOTES
	ID			ID			#IMPLIED
	name		CDATA		#IMPLIED
    locked      %boolean;           #IMPLIED
	indent   	CDATA 		#IMPLIED
>

<!ELEMENT DRAWING EMPTY>
<!ATTLIST DRAWING
	ID			ID			#IMPLIED
	name		CDATA		#IMPLIED
    locked      %boolean;           #IMPLIED
>

<!ELEMENT UNITCONV EMPTY>
<!ATTLIST UNITCONV
	ID			ID			#IMPLIED
	name		CDATA		#IMPLIED
    locked      %boolean;           #IMPLIED
>

<!ELEMENT IMAGE EMPTY>
<!ATTLIST IMAGE
	ID			ID			#REQUIRED
	name		CDATA		#IMPLIED
    locked      %boolean;           #IMPLIED
	url			CDATA		#IMPLIED
>

<!-- SuperNotes related declarations -->
<!ENTITY % snchildren "#PCDATA | SNPARAGRAPH | EMBOBJ | INDENT | BR">
<!ELEMENT SUPERNOTES (%snchildren;)*>
<!ATTLIST SUPERNOTES
	ID			ID			#REQUIRED
	name		CDATA		#IMPLIED
    locked      %boolean;           #IMPLIED
>
<!ELEMENT EMBOBJ (%SNOBJECTS;)?>
<!ATTLIST EMBOBJ
	object 			IDREF 			#IMPLIED
	w   			CDATA			#IMPLIED
	h   			CDATA			#IMPLIED
	alignment		(left | right) 	"left"
	wrapping   		%boolean; 		"false"
	link	   		%boolean; 		"false"
	linkcolor		CDATA			"0000FF"
>
<!ELEMENT SNPARAGRAPH (#PCDATA)>
<!ATTLIST SNPARAGRAPH
	link   		%boolean; 	"false"
	linkcolor  	CDATA 		"000000"
	object 		IDREF 		#IMPLIED
	indent   	CDATA 		#IMPLIED
>
<!ELEMENT EXPOBJECT EMPTY>
<!ATTLIST EXPOBJECT
	ID			ID			#REQUIRED
	url 		CDATA 		#REQUIRED
>
<!ELEMENT BR EMPTY>
<!ELEMENT INDENT (%snchildren;)*>
<!ATTLIST INDENT
    size                CDATA #IMPLIED
    first-line-offset   CDATA #IMPLIED
>

<!-- DataCollector and Graph related declarations -->
<!ELEMENT XAXIS EMPTY>
<!ATTLIST XAXIS
    min        CDATA        #IMPLIED
    max        CDATA        #IMPLIED
> 
<!ELEMENT YAXIS EMPTY>
<!ATTLIST YAXIS
    min        CDATA        #IMPLIED
    max        CDATA        #IMPLIED
> 

<!ELEMENT PROP EMPTY>
<!ATTLIST PROP 
   name       CDATA        #REQUIRED
    value      CDATA        #REQUIRED
>

<!ELEMENT PROBE (PROP)*>
<!ATTLIST PROBE
    ID         ID            #IMPLIED
    locked      %boolean;    #IMPLIED
    probe      %probes;      "Temperature"
    interface  (0 | 2)       "2"
>

<!ELEMENT INTPROBETRANS (PROBE)?>
<!ATTLIST INTPROBETRANS
    ID         ID            #IMPLIED
    quantity   CDATA         #REQUIRED
    probe      IDREF         #IMPLIED
>

<!ELEMENT DATAFOLDER EMPTY>
<!ATTLIST DATAFOLDER
    object     IDREF       #REQUIRED
>

<!ELEMENT LINE (PROBE | INTPROBETRANS | EXPOBJECT | OBJ-REF)?>
<!ATTLIST LINE
    xaxis      CDATA        #REQUIRED
    yaxis      CDATA        #REQUIRED
    datasource IDREF        #IMPLIED
>

<!ELEMENT GRAPH (DATAFOLDER?, (XAXIS | YAXIS | LINE)*)>
<!ATTLIST GRAPH
    current-line   CDATA    #IMPLIED
    title          CDATA    #IMPLIED
    locked      %boolean;           #IMPLIED
>

<!ELEMENT DATACOLLECTOR ((PROBE | INTPROBETRANS | EXPOBJECT | OBJ-REF)*,GRAPH)>
<!ATTLIST DATACOLLECTOR
	ID			ID			#IMPLIED
	name		CDATA		#IMPLIED
    locked      %boolean;           #IMPLIED
>

<!ELEMENT OBJ-REF EMPTY>
<!ATTLIST OBJ-REF
    ref         IDREF      #REQUIRED
>

=== concord-consortium/teemss/CCProbe/CCProbeXML/testsuite/labbook.xml
<?xml version="1.0"?><!DOCTYPE LABBOOK PUBLIC "-//Concord.ORG//DTD LabBook Description//EN" "../../../DTD/labbook.dtd"><LABBOOK>  <FOLDER ID="folder-ccprobe" name="CCProbe">    <FOLDER ID="folder-probes" name="Probes" view="paging">      <DATACOLLECTOR ID="dc-temperature" name="Temperature">	<GRAPH>	    <XAXIS min="0" max="60"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe1" probe="Temperature"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="dc-light-4000" name="Light - 4000 Lux">	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe2" probe="Light"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="dc-temperature2" name="Finger Temperatures">	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe3" probe="Temperature"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="dc-force-200" name="Force - 200 N" >	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe4" probe="Force"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="dc-force-20" name="Force - 20 N" >	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe5" probe="Force"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="dc-force-2" name="Force - 2 N" >	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe6" probe="Force"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="dc-smartwheel-pos" name="SmartWheel - Position" >	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe7" probe="SmartWheel"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="dc-smartwheel-vel" name="SmartWheel - Velocity" >	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe8" probe="SmartWheel"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="voltage-current-v" name="VoltageCurrent - Voltage" >	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe9" probe="VoltageCurrent"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="voltage-current-a" name="VoltageCurrent - Amps" >	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe10" probe="VoltageCurrent"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="voltage-current-w" name="VoltageCurrent - Watts" >	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe11" probe="VoltageCurrent"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DATACOLLECTOR ID="voltage-current-j" name="VoltageCurrent - Joules" >	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe12" probe="VoltageCurrent"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>    </FOLDER>    <FOLDER ID="folder-supernotes" name="SuperNotes" view="paging">      <SUPERNOTES ID="supernotes1" name="SuperNote1">	<SNPARAGRAPH linkcolor="0000FF">Positive or negative forces are applied to the free end of an aluminum beam which produce displacements proportional to applied force.  The displacement of a cylindrical magnet attached to the end of the beam is measured with a linear hall effect magnetic field sensor.  The long axis of the cylindrical magnet is oriented in parallel with the plane of the hall effect sensor and in line with the arc of displacement of the end of the beam.  The distance of the magnet from the active plane of the hall effect sensor should be 1/2 the length of the magnet for most linear response.  With this topology a linear relationship exists between displacement of the magnet and the voltage response of the hall effect sensor as long as the displacement is limited to prevent either end of the magnet from extending past the active area on the hall effect sensor.</SNPARAGRAPH>	<EMBOBJ w="64" h="64">	  <IMAGE ID="image1" name="image1" url="image.bmp"/>	</EMBOBJ>      </SUPERNOTES>      <SUPERNOTES ID="supernotes2" name="SuperNote2">	<SNPARAGRAPH linkcolor="0000FF">Positive or negative forces are applied to the free end of an aluminum beam which produce displacements proportional to applied force.  The displacement of a cylindrical magnet attached to the end of the beam is measured with a linear hall effect magnetic field sensor.  The long axis of the cylindrical magnet is oriented in parallel with the plane of the hall effect sensor and in line with the arc of displacement of the end of the beam.  The distance of the magnet from the active plane of the hall effect sensor should be 1/2 the length of the magnet for most linear response.  With this topology a linear relationship exists between displacement of the magnet and the voltage response of the hall effect sensor as long as the displacement is limited to prevent either end of the magnet from extending past the active area on the hall effect sensor.</SNPARAGRAPH>	<EMBOBJ object="image1" w="64" h="64"/>	<SNPARAGRAPH linkcolor="0000FF">About our only hope is to call Clue Express with a Class One Code Red Clue Alert and get them to immediately send over the Clue Fairy to bonk them on the head with her Clue Mallet and drag them to the Clue Fields where she will drench them in Clue Musk while blowing the mating call of the Wild Clue on her Clue Whistle.</SNPARAGRAPH>      </SUPERNOTES>    </FOLDER>    <FOLDER ID="folder-sample-objects" name="Sample Objects" view="paging">      <DATACOLLECTOR ID="dc-temperature1" name="Temperature" >	<GRAPH>	    <XAXIS min="0" max="600"/>	    <YAXIS min="10" max="40"/>	    <LINE xaxis="0" yaxis="0">	      <PROBE ID="probe13" probe="Temperature"/>	    </LINE>	  </GRAPH>      </DATACOLLECTOR>      <DRAWING ID="draw-my-drawing" name="My Drawing"/>      <UNITCONV ID="unit-1" name="Unit Convertor"/>      <NOTES ID="notes-my-note" name="My Notes"/>      <FOLDER ID="folder-another" name="Another Folder">	<DRAWING ID="draw-1" name="My Drawing 1"/>	<DRAWING ID="draw-2" name="My Drawing 2"/>	<FOLDER ID="folder-deep" name="Deeply Buried Folder">	  <DRAWING ID="draw-3" name="My Drawing 3"/>	  <DRAWING ID="draw-4" name="My Drawing 4"/>	</FOLDER>      </FOLDER>    </FOLDER>  </FOLDER>  <FOLDER ID="folder-tracker" name="Tracker" view="paging">    <SUPERNOTES ID="tracker-introduction" name="Introduction">      <EMBOBJ w="158" h="12">	<IMAGE ID="palm-titlebar" name="image1" url="tracker-images/PALM_titleBar.bmp"/>      </EMBOBJ>      <SNPARAGRAPH linkcolor="0000FF">Discovery Question: </SNPARAGRAPH>      <SNPARAGRAPH/>      <EMBOBJ w="140" h="124">	<IMAGE ID="WEB_smallCart.bmp" name="WEB_smallCart.bmp" url="tracker-images/WEB_smallCart.bmp"/>      </EMBOBJ>      <SNPARAGRAPH/>      <SNPARAGRAPH linkcolor="0000FF">What can be learned from position versus time and velocity versus time graphs of a moving cart?</SNPARAGRAPH>      <SNPARAGRAPH/>      <SNPARAGRAPH linkcolor="0000FF">In this activity you will generate and analyze simple, straight-line motions by using a SmartWheel.</SNPARAGRAPH>    </SUPERNOTES>    <SUPERNOTES ID="tracker-thinking" name="Thinking">      <EMBOBJ object="palm-titlebar" w="158" h="12"/>      <SNPARAGRAPH linkcolor="0000FF">Thinking About the Question</SNPARAGRAPH>      <SNPARAGRAPH/>      <SNPARAGRAPH linkcolor="0000FF">What can be learned from position versus time and velocity versus time graphs of a moving cart?</SNPARAGRAPH>      <SNPARAGRAPH/>      <SNPARAGRAPH linkcolor="0000FF">Can you tell exactly how far or fast your cart is moving without using a meter stick and stop watch? How do you know it's speed at any given time? By watching your cart move, is it possible to know when it is slowing down? Would it be more useful to know it's position at each moment, or it's velocity? Could you get one from the other? Discuss these questions with your group and write down some of your ideas in Notes on your handheld computer to share with your group.</SNPARAGRAPH>      <SNPARAGRAPH/>      <SNPARAGRAPH linkcolor="0000FF">The following position versus time graph of a cart was made with a SmartWheel. Discuss the motion shown with your group. Did the cart appear to change velocity at anytime? Draw the graph in Notes on your handheld computer and label parts of the graph that you understand or have questions about. </SNPARAGRAPH>      <SNPARAGRAPH/>      <EMBOBJ w="100" h="98">	<IMAGE ID="graconstant.bmp" name="graconstant.bmp" url="tracker-images/graconstant.bmp"/>      </EMBOBJ>      <SNPARAGRAPH/>      <EMBOBJ link="true" linkcolor="FF0000">	<DRAWING ID="tracker-thinking-drawing" name="Draw and Label Your Own Graph"/>      </EMBOBJ>    </SUPERNOTES>    <SUPERNOTES ID="tracker-materials" name="Materials">      <EMBOBJ object="palm-titlebar" w="158" h="12"/>      <SNPARAGRAPH linkcolor="0000FF">Tracker Materials</SNPARAGRAPH>      <SNPARAGRAPH/>      <SNPARAGRAPH linkcolor="0000FF">- CC SmartWheel removed from air cart</SNPARAGRAPH>      <SNPARAGRAPH linkcolor="0000FF">- meter stick</SNPARAGRAPH>      <SNPARAGRAPH linkcolor="0000FF">- tape</SNPARAGRAPH>      <SNPARAGRAPH linkcolor="0000FF">- CC SmartWheel installed on air cart</SNPARAGRAPH>      <SNPARAGRAPH linkcolor="0000FF">- CC probe software</SNPARAGRAPH>      <SNPARAGRAPH linkcolor="0000FF">- handheld comp
